version: '3'
services:
  wemo-controller:
    build:
        context: ./wemo-controller
    image: ml-catfeeder/wemo-controller
    network_mode: "host"
    env_file: .env
    ports:
    - "8000:8000"
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 100
        window: 10s
  darknet-detector:
    build:
        context: ./darknet-decoder
    image: ml-catfeeder/darknet-decoder
    network_mode: "host"
    env_file: .env
    ports:
    - "9080:9080"
    - "9070:9070"
    privileged: true
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 100
        window: 10s
  web-interface:
    build:
      context: ./web-interface
    image: ml-catfeeder/web-interface
    network_mode: "host"
    env_file: .env
    ports:
    - "10080:10080"
    privileged: true
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 100
        window: 10s
  logic-controller:
    build:
      context: ./logic-controller
    image: ml-catfeeder/logic-controller
    network_mode: "host"
    env_file: .env
    deploy:
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 100
        window: 10s
